In [41]:
# import the lib
import pandas as pd
import numpy as np

In [42]:
# import the dataset
dataset = pd.read_csv("TRAIN.csv")

In [43]:
dataset

ID  Store_id Store_Type Location_Type Region_Code        Date  \
0       T1000001         1         S1            L3          R1  2018-01-01   
1       T1000002       253         S4            L2          R1  2018-01-01   
2       T1000003       252         S3            L2          R1  2018-01-01   
3       T1000004       251         S2            L3          R1  2018-01-01   
4       T1000005       250         S2            L3          R4  2018-01-01   
...          ...       ...        ...           ...         ...         ...   
188335  T1188336       149         S2            L3          R2  2019-05-31   
188336  T1188337       153         S4            L2          R1  2019-05-31   
188337  T1188338       154         S1            L3          R2  2019-05-31   
188338  T1188339       155         S3            L1          R2  2019-05-31   
188339  T1188340       152         S2            L1          R1  2019-05-31   

        Holiday Discount  #Order     Sales  
0             1      Yes       9   7011.84  
1             1      Yes      60  51789.12  
2             1      Yes      42  36868.20  
3             1      Yes      23  19715.16  
4             1      Yes      62  45614.52  
...         ...      ...     ...       ...  
188335        1      Yes      51  37272.00  
188336        1       No      90  54572.64  
188337        1       No      56  31624.56  
188338        1      Yes      70  49162.41  
188339        1       No      47  37977.00  

[188340 rows x 10 columns]

In [44]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188340 entries, 0 to 188339
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   ID             188340 non-null  object 
 1   Store_id       188340 non-null  int64  
 2   Store_Type     188340 non-null  object 
 3   Location_Type  188340 non-null  object 
 4   Region_Code    188340 non-null  object 
 5   Date           188340 non-null  object 
 6   Holiday        188340 non-null  int64  
 7   Discount       188340 non-null  object 
 8   #Order         188340 non-null  int64  
 9   Sales          188340 non-null  float64
dtypes: float64(1), int64(3), object(6)
memory usage: 14.4+ MB


In [45]:
dataset.isnull().sum()

ID               0
Store_id         0
Store_Type       0
Location_Type    0
Region_Code      0
Date             0
Holiday          0
Discount         0
#Order           0
Sales            0
dtype: int64

In [46]:
# pip install plotly
import plotly.express as px

In [47]:
pie1 = dataset["Store_Type"].value_counts()
store = pie1.index
orders = pie1.values

fig = px.pie(dataset, values= orders, names=store)
fig.show()

In [48]:
pie2 = dataset["Location_Type"].value_counts()
location = pie2.index
orders = pie2.values

fig = px.pie(dataset, values= orders, names=location)
fig.show()

In [49]:
pie3 = dataset["Holiday"].value_counts()
holiday = pie3.index
orders = pie3.values

fig = px.pie(dataset, values= orders, names=holiday)
fig.show()

In [50]:
pie3 = dataset["Holiday"].value_counts()
holiday = pie3.index
orders = pie3.values

fig = px.pie(dataset, values= orders, names=holiday)
fig.show()

In [51]:
pie4 = dataset["Discount"].value_counts()
discount = pie4.index
orders = pie4.values

fig = px.pie(dataset, values= orders, names=discount)
fig.show()

In [52]:
dataset["Discount"] = dataset["Discount"].map({"NO" : 0, "Yes" : 1})

In [53]:
dataset

ID  Store_id Store_Type Location_Type Region_Code        Date  \
0       T1000001         1         S1            L3          R1  2018-01-01   
1       T1000002       253         S4            L2          R1  2018-01-01   
2       T1000003       252         S3            L2          R1  2018-01-01   
3       T1000004       251         S2            L3          R1  2018-01-01   
4       T1000005       250         S2            L3          R4  2018-01-01   
...          ...       ...        ...           ...         ...         ...   
188335  T1188336       149         S2            L3          R2  2019-05-31   
188336  T1188337       153         S4            L2          R1  2019-05-31   
188337  T1188338       154         S1            L3          R2  2019-05-31   
188338  T1188339       155         S3            L1          R2  2019-05-31   
188339  T1188340       152         S2            L1          R1  2019-05-31   

        Holiday  Discount  #Order     Sales  
0             1       1.0       9   7011.84  
1             1       1.0      60  51789.12  
2             1       1.0      42  36868.20  
3             1       1.0      23  19715.16  
4             1       1.0      62  45614.52  
...         ...       ...     ...       ...  
188335        1       1.0      51  37272.00  
188336        1       NaN      90  54572.64  
188337        1       NaN      56  31624.56  
188338        1       1.0      70  49162.41  
188339        1       NaN      47  37977.00  

[188340 rows x 10 columns]

In [54]:
dataset["Store_Type"] = dataset["Store_Type"].map({"S1" : 1, "S2" : 2, "S3" : 3, "S4" : 4,})

In [55]:
dataset

ID  Store_id  Store_Type Location_Type Region_Code        Date  \
0       T1000001         1           1            L3          R1  2018-01-01   
1       T1000002       253           4            L2          R1  2018-01-01   
2       T1000003       252           3            L2          R1  2018-01-01   
3       T1000004       251           2            L3          R1  2018-01-01   
4       T1000005       250           2            L3          R4  2018-01-01   
...          ...       ...         ...           ...         ...         ...   
188335  T1188336       149           2            L3          R2  2019-05-31   
188336  T1188337       153           4            L2          R1  2019-05-31   
188337  T1188338       154           1            L3          R2  2019-05-31   
188338  T1188339       155           3            L1          R2  2019-05-31   
188339  T1188340       152           2            L1          R1  2019-05-31   

        Holiday  Discount  #Order     Sales  
0             1       1.0       9   7011.84  
1             1       1.0      60  51789.12  
2             1       1.0      42  36868.20  
3             1       1.0      23  19715.16  
4             1       1.0      62  45614.52  
...         ...       ...     ...       ...  
188335        1       1.0      51  37272.00  
188336        1       NaN      90  54572.64  
188337        1       NaN      56  31624.56  
188338        1       1.0      70  49162.41  
188339        1       NaN      47  37977.00  

[188340 rows x 10 columns]

In [56]:
dataset["Location_Type"] = dataset["Location_Type"].map({"L1" : 1, "L2" : 2, "L3" : 3, "L4" : 4, "L5" : 5})

In [57]:
dataset["Location_Type"] = dataset["Location_Type"].map({"L1" : 1, "L2" : 2, "L3" : 3, "L4" : 4, "L5" : 5})

In [58]:
dataset

ID  Store_id  Store_Type  Location_Type Region_Code        Date  \
0       T1000001         1           1            NaN          R1  2018-01-01   
1       T1000002       253           4            NaN          R1  2018-01-01   
2       T1000003       252           3            NaN          R1  2018-01-01   
3       T1000004       251           2            NaN          R1  2018-01-01   
4       T1000005       250           2            NaN          R4  2018-01-01   
...          ...       ...         ...            ...         ...         ...   
188335  T1188336       149           2            NaN          R2  2019-05-31   
188336  T1188337       153           4            NaN          R1  2019-05-31   
188337  T1188338       154           1            NaN          R2  2019-05-31   
188338  T1188339       155           3            NaN          R2  2019-05-31   
188339  T1188340       152           2            NaN          R1  2019-05-31   

        Holiday  Discount  #Order     Sales  
0             1       1.0       9   7011.84  
1             1       1.0      60  51789.12  
2             1       1.0      42  36868.20  
3             1       1.0      23  19715.16  
4             1       1.0      62  45614.52  
...         ...       ...     ...       ...  
188335        1       1.0      51  37272.00  
188336        1       NaN      90  54572.64  
188337        1       NaN      56  31624.56  
188338        1       1.0      70  49162.41  
188339        1       NaN      47  37977.00  

[188340 rows x 10 columns]

In [59]:
X = np.array(dataset[["Store_Type", "Location_Type", "Holiday", "Discount"]])
y = np.array(dataset["#Order"])

In [60]:
X

array([[ 1., nan,  1.,  1.],
       [ 4., nan,  1.,  1.],
       [ 3., nan,  1.,  1.],
       ...,
       [ 1., nan,  1., nan],
       [ 3., nan,  1.,  1.],
       [ 2., nan,  1., nan]])

In [61]:
y

array([ 9, 60, 42, ..., 56, 70, 47], dtype=int64)

In [62]:
from sklearn.model_selection import train_test_split

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=10)

In [64]:
len(X_train)

141255

In [65]:
pip install lightgbm

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [66]:
import lightgbm as ltb

In [67]:
model = ltb.LGBMRegressor()

In [68]:
model.fit(X_train, y_train)

LGBMRegressor()

In [69]:
y_pred = model.predict(X_test)

In [70]:
y_pred

array([ 37.39876244, 116.66702474,  53.60432013, ...,  53.55366935,
        95.50144015, 116.66702474])

In [71]:
y_test

array([ 37, 111,  41, ...,  85,  95, 130], dtype=int64)

In [72]:
acc = model.score(X_test,y_test)

In [73]:
acc

0.5771276573008557

In [74]:
data = pd.DataFrame(data={"Predicted Orders": y_pred.flatten()})

In [75]:
data

Predicted Orders
0             37.398762
1            116.667025
2             53.604320
3             67.699161
4            116.667025
...                 ...
47080         95.501440
47081         53.553669
47082         53.553669
47083         95.501440
47084        116.667025

[47085 rows x 1 columns]

In [76]:
new_data = np.array([[2, 4, 1, 0],[1, 2, 0, 1]])

In [77]:
new_data

array([[2, 4, 1, 0],
       [1, 2, 0, 1]])

In [78]:
y_pred_new = model.predict(new_data)

In [79]:
y_pred_new

array([31.26922713, 66.75834193])